language: perl
perl:
  - "5.8"
  - "5.8.7"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "dev"
script: 'perl Makefile.PL; make test'
branches:
  only:
    - master
